name: Code checks

on:
  push:
    branches: [askat]
  pull_request:
    branches: [askat]

jobs:
  test:
    runs-on: windows 10
    steps:
      - uses: action/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
      - run: npm ci
      - run: npm test
